config/routes.rb
Rails.application.routes.draw do
  resources :playlists, only: [:index, :show, :destroy]
  get '/profile', to: 'users#profile'
  get '/logout', to: 'users#logout'
  get '/auth/spotify/callback', to: 'users#spotify'
  post '/make_playlist', to: 'playlists#create'
  root "welcome#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>TravelTracks</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <% if session['spotify_user'] %>
      <div class="alert"><p id="alert">Please enter playlist length manually until further notice.</p></div>

      <% if flash[:notice] %>
        <div class="alert">
            <p id="notice"><%= flash[:notice] %></p>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert">
            <p id="alert"><%= flash[:alert] %></p>
        </div>
      <% end %>
      
      <div id="main">
        
        <header>
          <div id="header">
            <div id="left-nav">
              <%= link_to "Home", root_path, id: "home-link" %>
              <%= link_to image_tag("ios7-albums-outline-s.png", size:"22x22", class: "nav-icon") + "My Playlists", playlists_path, id: "my-playlists-link" %>
            </div>
                
            <div id="user-nav">
              <%= link_to session[:spotify_user_id], profile_path %>
              <%= link_to "Logout", logout_path, id: "logout-link" %>
            </div>
                
          </div>
        </header>
          
        <%= yield %>
        
        <footer>
          <div id="footer-content">
            Copyright <%= Time.now.year %> TravelTracks
          </div>
        </footer>
      </div>
    <% else %>
      <div id="spotify-login-div">
        <div id="login-wrap">
          <%= link_to "Sign in to Spotify", '/auth/spotify', class: "sign-in" %>
          <div id="login-details">
            <p>Travel Tracks needs your permission to access your Spotify library. For every playlist generated, TravelTracks logs your Spotify user ID and your playlist ID.</p>
          </div>
        </div>
      </div>
    <% end %>

  </body>
</html>